apiVersion: v1
kind: Service
metadata:
  name: gethnode
  namespace: chainrpc
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websoket
  clusterIP: None
  selector:
    app: gethnode
