apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gethnode
  namespace: chainrpc
spec:
  selector:
    matchLabels:
      app: gethnode
  replicas: 1
  serviceName: gethnode
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gethnode
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: geth
          image: docker.io/ethereum/client-go
          imagePullPolicy: Always
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args:
            [
              "--http",
              "--http.addr=0.0.0.0",
              "--http.api=eth,net,web3",
              "--http.vhosts=*",
              "--http.corsdomain=*",
              "--ws",
              "--ws.addr=0.0.0.0",
              "--ws.api=eth,net,web3",
              "--ws.origins=*",
              "--graphql",
              "--graphql.corsdomain=*",
              "--graphql.vhosts=*",
            ]
          resources:
            requests:
              memory: 2G
              cpu: 1000m
            limits:
              memory: 16G
              cpu: 8000m
          livenessProbe:
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          volumeMounts:
            - name: chaindata
              mountPath: /root/.ethereum
      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata-gethnode
