version: "4"

services:
  rpc_node:
    image: ethereum/client-go:v1.10.23
    pull_policy: always
    container_name: ${RPC_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
    volumes:
      - ${DATA_DIR:-/data/rpc}:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --http
      - --http.api
      - "debug,net,eth,web3,txpool"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3,debug,txpool"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      # - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      # - --maxpeers=100
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=full
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      - --gcmode=archive
      - --bootnodes
      - ${RPC_BOOT_NODES}
      - --networkid=${RPC_CHAIN_ID}
      - --txpool.pricelimit=0
      - --ignore-legacy-receipts
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"