version: "4"

services:
  signer2:
    image: ethereum/client-go:stable
    pull_policy: always
    container_name: ${SIGNER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${SIGNER_INTERNAL_IP}:${SIGNER_ETH_PORT}:30303"
      - "${SIGNER_INTERNAL_IP}:${SIGNER_ETH_PORT}:30303/udp"
      - "${SIGNER_INTERNAL_IP}:${SIGNER_JSON_RPC_PORT}:8545"
      - "${SIGNER_INTERNAL_IP}:${SIGNER_WEBSOCKET_PORT}:8546"
    volumes:
      - ${DATA_DIR:-/data/signer}:/root/.ethereum
      - ${SIGNER_PASSWORD_PATH:-/root/password.txt}:/root/password.txt
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      # - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      # - --maxpeers=100
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=full
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      - --gcmode=full
      - --networkid=${SIGNER_CHAIN_ID}
      - --nat
      - extip:${SIGNER_INTERNAL_IP}
      - --unlock
      - ${SIGNER_ADDRESS}
      - --password
      - /root/password.txt
      - --mine
      - --miner.gasprice=0
      - --miner.etherbase=${SIGNER_ADDRESS}
      - --bootnodes
      - ${SIGNER_BOOT_NODES}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
