name: ci

on:
  push:
    paths-ignore:
      - ".github"
    branches:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  main:
    concurrency: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: islishude
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        if: ${{ github.ref_type == 'branch' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: islishude/geth:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build with tag and push
        id: docker_build_with_tag
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: islishude/web3-cli:${{ github.ref_name }}
